In [2]:
import json
import plotly
import pandas as pd

from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

from flask import Flask
from flask import render_template, request, jsonify
from plotly.graph_objs import Bar
import joblib
from sqlalchemy import create_engine
engine = create_engine('sqlite:///../data/DisasterMessages.db')
df = pd.read_sql_table('disastertab', engine)

In [3]:
genre_counts = df.groupby('genre').count()['message']
genre_names = list(genre_counts.index)

In [9]:
df_1=df.drop(columns={'id','message','original','genre'})

In [32]:
columns=[]
number_of_occureance=[]
for column in df_1.columns:
   columns.append(column)
   number_of_occureance.append(df_1[column].sum())

In [33]:
vis_2=pd.DataFrame({'Feature':columns,'number_of_occureance':number_of_occureance})

                   Feature  number_of_occureance
0                  related               19906.0
1                  request                4474.0
2                    offer                 118.0
3              aid_related               10860.0
4             medical_help                2084.0
5         medical_products                1313.0
6        search_and_rescue                 724.0
7                 security                 471.0
8                 military                 860.0
9              child_alone                   0.0
10                   water                1672.0
11                    food                2923.0
12                 shelter                2314.0
13                clothing                 405.0
14                   money                 604.0
15          missing_people                 298.0
16                refugees                 875.0
17                   death                1194.0
18               other_aid                3446.0
19  infrastructure_related                1705.0
20               transport                1201.0
21               buildings                1333.0
22             electricity                 532.0
23                   tools                 159.0
24               hospitals                 283.0
25                   shops                 120.0
26             aid_centers                 309.0
27    other_infrastructure                1151.0
28         weather_related                7297.0
29                  floods                2155.0
30                   storm                2443.0
31                    fire                 282.0
32              earthquake                2455.0
33                    cold                 530.0
34           other_weather                1376.0
35           direct_report                5075.0

In [8]:
df

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26211,30261,The training demonstrated how to enhance micro...,None,news,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26212,30262,A suitable candidate has been selected and OCH...,None,news,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26213,30263,"Proshika, operating in Cox's Bazar municipalit...",None,news,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26214,30264,"Some 2,000 women protesting against the conduc...",None,news,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26215,30265,A radical shift in thinking came about as a re...,None,news,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0